### ISSUE TITLE
having this error. can u help? thx.

### ISSUE THREAD

**Issue by hiqsociety** [estraier/tkrzw-go#1]
go build
# pkg-config --cflags  -- tkrzw
Package tkrzw was not found in the pkg-config search path.
Perhaps you should add the directory containing `tkrzw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tkrzw' found
pkg-config: exit status 1
make: *** [Makefile:13: build] Error 2

**Comment by estraier** [comment]
Please set PKG_CONFIG_PATH in your .profile or somewhere.
