### ISSUE TITLE
FileIndex availability

### ISSUE THREAD

**Issue by reginaldl** [estraier/tkrzw-go#3]
Hi,

I don't seem to find tkrzw's `FileIndex` in the Go API. Is this intentional? Is there any plan to include it?

Thanks!

**Comment by estraier** [comment]
Hi,
The Go interface is a wrapper of the C interface.  And, the C interface doesn't support FileIndex yet.
Now, I'm writing a class PolyDBM which wraps both FileIndex and MemIndex.
I'm going to write its C and Go interafaces soon.

**Comment by reginaldl** [comment]
Exciting! Thank you so much!

**Comment by estraier** [comment]
I released Tkrzw 1.0.28, which supports PolyIndex to wrap FileIndex and MemIndex.
The Go interface on Github supports Index class to access PolyIndex.

**Comment by reginaldl** [comment]
That was fast! I'll check it out. Thank you so much!
